"""Create database

Revision ID: 073f4bdec491
Revises: 6ff1091e78be
Create Date: 2018-11-27 23:35:34.982306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073f4bdec491'
down_revision = '6ff1091e78be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot_data', sa.Column('robot_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_robot_data_robot_id'), 'robot_data', ['robot_id'], unique=False)
    op.create_foreign_key(None, 'robot_data', 'master_app_robot', ['robot_id'], ['robot_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'robot_data', type_='foreignkey')
    op.drop_index(op.f('ix_robot_data_robot_id'), table_name='robot_data')
    op.drop_column('robot_data', 'robot_id')
    # ### end Alembic commands ###
