"""Create database

Revision ID: 0c35d74fec94
Revises: 78be8c8b27ee
Create Date: 2018-12-02 11:48:58.902173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c35d74fec94'
down_revision = '78be8c8b27ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('master_app_robot_rescanning_robot_id_fkey', 'master_app_robot_rescanning', type_='foreignkey')
    op.create_foreign_key(None, 'master_app_robot_rescanning', 'master_app_robot', ['robot_id'], ['robot_id'], ondelete='CASCADE')
    op.drop_constraint('robot_data_robot_id_fkey', 'robot_data', type_='foreignkey')
    op.create_foreign_key(None, 'robot_data', 'master_app_robot', ['robot_id'], ['robot_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'robot_data', type_='foreignkey')
    op.create_foreign_key('robot_data_robot_id_fkey', 'robot_data', 'master_app_robot', ['robot_id'], ['robot_id'])
    op.drop_constraint(None, 'master_app_robot_rescanning', type_='foreignkey')
    op.create_foreign_key('master_app_robot_rescanning_robot_id_fkey', 'master_app_robot_rescanning', 'master_app_robot', ['robot_id'], ['robot_id'])
    # ### end Alembic commands ###
