"""Create database

Revision ID: 26bfb2d637aa
Revises: 073f4bdec491
Create Date: 2018-11-29 10:59:28.169020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26bfb2d637aa'
down_revision = '073f4bdec491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('robot_data', sa.Column('data_hash', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_robot_data_data_hash'), 'robot_data', ['data_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robot_data_data_hash'), table_name='robot_data')
    op.drop_column('robot_data', 'data_hash')
    # ### end Alembic commands ###
