"""Create database

Revision ID: 6ca59607f344
Revises: 
Create Date: 2018-11-27 00:57:38.247141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca59607f344'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_app_company',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_app_company_company_id'), 'master_app_company', ['company_id'], unique=True)
    op.create_index(op.f('ix_master_app_company_id'), 'master_app_company', ['id'], unique=False)
    op.create_index(op.f('ix_master_app_company_product_id'), 'master_app_company', ['product_id'], unique=False)
    op.create_table('master_app_robot',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.Column('robot_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_app_robot_company_id'), 'master_app_robot', ['company_id'], unique=False)
    op.create_index(op.f('ix_master_app_robot_id'), 'master_app_robot', ['id'], unique=False)
    op.create_index(op.f('ix_master_app_robot_product_id'), 'master_app_robot', ['product_id'], unique=False)
    op.create_index(op.f('ix_master_app_robot_robot_id'), 'master_app_robot', ['robot_id'], unique=True)
    op.create_table('robot_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['master_app_company.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robot_data_company_id'), 'robot_data', ['company_id'], unique=False)
    op.create_index(op.f('ix_robot_data_created_at'), 'robot_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_robot_data_id'), 'robot_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_robot_data_id'), table_name='robot_data')
    op.drop_index(op.f('ix_robot_data_created_at'), table_name='robot_data')
    op.drop_index(op.f('ix_robot_data_company_id'), table_name='robot_data')
    op.drop_table('robot_data')
    op.drop_index(op.f('ix_master_app_robot_robot_id'), table_name='master_app_robot')
    op.drop_index(op.f('ix_master_app_robot_product_id'), table_name='master_app_robot')
    op.drop_index(op.f('ix_master_app_robot_id'), table_name='master_app_robot')
    op.drop_index(op.f('ix_master_app_robot_company_id'), table_name='master_app_robot')
    op.drop_table('master_app_robot')
    op.drop_index(op.f('ix_master_app_company_product_id'), table_name='master_app_company')
    op.drop_index(op.f('ix_master_app_company_id'), table_name='master_app_company')
    op.drop_index(op.f('ix_master_app_company_company_id'), table_name='master_app_company')
    op.drop_table('master_app_company')
    # ### end Alembic commands ###
