"""Create database

Revision ID: 78be8c8b27ee
Revises: aeac98e5a33f
Create Date: 2018-12-02 01:25:34.596271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78be8c8b27ee'
down_revision = 'aeac98e5a33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_app_robot_rescanning',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('rescan_start', sa.DateTime(), nullable=True),
    sa.Column('rescan_end', sa.DateTime(), nullable=True),
    sa.Column('activate_rescan', sa.Boolean(), nullable=True),
    sa.Column('rescan_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['robot_id'], ['master_app_robot.robot_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_app_robot_rescanning_created_at'), 'master_app_robot_rescanning', ['created_at'], unique=False)
    op.create_index(op.f('ix_master_app_robot_rescanning_id'), 'master_app_robot_rescanning', ['id'], unique=False)
    op.create_index(op.f('ix_master_app_robot_rescanning_robot_id'), 'master_app_robot_rescanning', ['robot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_app_robot_rescanning_robot_id'), table_name='master_app_robot_rescanning')
    op.drop_index(op.f('ix_master_app_robot_rescanning_id'), table_name='master_app_robot_rescanning')
    op.drop_index(op.f('ix_master_app_robot_rescanning_created_at'), table_name='master_app_robot_rescanning')
    op.drop_table('master_app_robot_rescanning')
    # ### end Alembic commands ###
