"""Create database

Revision ID: 9d54bfdcc4c7
Revises: 0c35d74fec94
Create Date: 2019-01-27 17:49:53.831310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d54bfdcc4c7'
down_revision = '0c35d74fec94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_app_robot_notification',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email_1', sa.String(length=100), nullable=True),
    sa.Column('email_2', sa.String(length=100), nullable=True),
    sa.Column('email_3', sa.String(length=100), nullable=True),
    sa.Column('email_4', sa.String(length=100), nullable=True),
    sa.Column('email_5', sa.String(length=100), nullable=True),
    sa.Column('error', sa.Boolean(), nullable=True),
    sa.Column('warning', sa.Boolean(), nullable=True),
    sa.Column('info', sa.Boolean(), nullable=True),
    sa.Column('robot_activity', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_app_robot_notification_created_at'), 'master_app_robot_notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_master_app_robot_notification_id'), 'master_app_robot_notification', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_app_robot_notification_id'), table_name='master_app_robot_notification')
    op.drop_index(op.f('ix_master_app_robot_notification_created_at'), table_name='master_app_robot_notification')
    op.drop_table('master_app_robot_notification')
    # ### end Alembic commands ###
