"""Create database

Revision ID: aeac98e5a33f
Revises: 26bfb2d637aa
Create Date: 2018-12-02 00:27:28.074031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeac98e5a33f'
down_revision = '26bfb2d637aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
